package edu.harvard.fas.rbrady.tpteam.tpbridge.hibernate;

// Generated Nov 10, 2006 5:22:58 PM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * TestType generated by hbm2java
 */
public class TestType implements java.io.Serializable {

	// Fields    

	private static final long serialVersionUID = 1L;

	private int id;

	private String name;

	private Set<Test> tests = new HashSet<Test>(0);

	// Constructors

	/** default constructor */
	public TestType() {
	}

	/** minimal constructor */
	public TestType(int id) {
		this.id = id;
	}

	/** full constructor */
	public TestType(int id, String name, Set<Test> tests) {
		this.id = id;
		this.name = name;
		this.tests = tests;
	}

	// Property accessors
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Test> getTests() {
		return this.tests;
	}

	public void setTests(Set<Test> tests) {
		this.tests = tests;
	}

}
