package edu.harvard.fas.rbrady.tpteam.tpbridge.hibernate;

// Generated Nov 10, 2006 5:22:58 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * Token generated by hbm2java
 */
public class Token implements java.io.Serializable {

	// Fields    

	private static final long serialVersionUID = 1L;

	private TokenId id;

	private TpteamUser tpteamUser;

	private Date createdDate;

	private String hostIpAddr;

	// Constructors

	/** default constructor */
	public Token() {
	}

	/** minimal constructor */
	public Token(TokenId id, TpteamUser tpteamUser) {
		this.id = id;
		this.tpteamUser = tpteamUser;
	}

	/** full constructor */
	public Token(TokenId id, TpteamUser tpteamUser, Date createdDate,
			String hostIpAddr) {
		this.id = id;
		this.tpteamUser = tpteamUser;
		this.createdDate = createdDate;
		this.hostIpAddr = hostIpAddr;
	}

	// Property accessors
	public TokenId getId() {
		return this.id;
	}

	public void setId(TokenId id) {
		this.id = id;
	}

	public TpteamUser getTpteamUser() {
		return this.tpteamUser;
	}

	public void setTpteamUser(TpteamUser tpteamUser) {
		this.tpteamUser = tpteamUser;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getHostIpAddr() {
		return this.hostIpAddr;
	}

	public void setHostIpAddr(String hostIpAddr) {
		this.hostIpAddr = hostIpAddr;
	}

}
