package edu.harvard.fas.rbrady.tpteam.tpbridge.hibernate;

// Generated Nov 10, 2006 5:22:58 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TpteamUser generated by hbm2java
 */
public class TpteamUser implements java.io.Serializable, Comparable<TpteamUser> {

	// Fields

	private static final long serialVersionUID = 1L;

	private int id;

	private Role role;

	private String userName;

	private String firstName;

	private String lastName;

	private String password;

	private String ecfId;

	private String phone;

	private String email;

	private Integer createdBy;

	private Date createdDate;

	private Integer modifiedBy;

	private Date modifiedDate;

	private Set<Project> projects = new HashSet<Project>(0);

	private Set<TestExecution> testExecutions = new HashSet<TestExecution>(0);

	private Set<Test> tests = new HashSet<Test>(0);

	private Set<Token> tokens = new HashSet<Token>(0);

	// Constructors

	/** default constructor */
	public TpteamUser() {
	}

	/** minimal constructor */
	public TpteamUser(int id) {
		this.id = id;
	}

	/** full constructor */
	public TpteamUser(int id, Role role, String userName, String firstName,
			String lastName, String password, String ecfId, String phone,
			String email, Integer createdBy, Date createdDate,
			Integer modifiedBy, Date modifiedDate, Set<Project> projects,
			Set<TestExecution> testExecutions, Set<Test> tests,
			Set<Token> tokens) {
		this.id = id;
		this.role = role;
		this.userName = userName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.ecfId = ecfId;
		this.phone = phone;
		this.email = email;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.projects = projects;
		this.testExecutions = testExecutions;
		this.tests = tests;
		this.tokens = tokens;
	}

	// Property accessors
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEcfId() {
		return this.ecfId;
	}

	public void setEcfId(String ecfId) {
		this.ecfId = ecfId;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Integer getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Integer modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	public void addToProject(Project project) {
		this.getProjects().add(project);
		project.getTpteamUsers().add(this);
	}

	public void addProject(Project project) {
		this.getProjects().add(project);
	}

	public void removeFromProject(Project project) {
		this.getProjects().remove(project);
		project.getTpteamUsers().remove(this);
	}

	public Set<TestExecution> getTestExecutions() {
		return this.testExecutions;
	}

	public void setTestExecutions(Set<TestExecution> testExecutions) {
		this.testExecutions = testExecutions;
	}

	public Set<Test> getTests() {
		return this.tests;
	}

	public void setTests(Set<Test> tests) {
		this.tests = tests;
	}

	public Set<Token> getTokens() {
		return this.tokens;
	}

	public void setTokens(Set<Token> tokens) {
		this.tokens = tokens;
	}

	public int compareTo(TpteamUser user) {
		if(this.lastName.compareTo(user.getLastName()) != 0)
			return this.lastName.compareTo(user.getLastName());
		else
			return this.firstName.compareTo(user.getFirstName());
	}
}
