package edu.harvard.fas.rbrady.tpteam.tpbridge.hibernate;

// Generated Nov 10, 2006 5:22:58 PM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	// Fields    

	private static final long serialVersionUID = 1L;

	private int roleId;

	private String name;

	private String description;

	private Set<TpteamUser> tpteamUsers = new HashSet<TpteamUser>(0);

	// Constructors

	/** default constructor */
	public Role() {
	}

	/** minimal constructor */
	public Role(int roleId) {
		this.roleId = roleId;
	}

	/** full constructor */
	public Role(int roleId, String name, String description,
			Set<TpteamUser> tpteamUsers) {
		this.roleId = roleId;
		this.name = name;
		this.description = description;
		this.tpteamUsers = tpteamUsers;
	}

	// Property accessors
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<TpteamUser> getTpteamUsers() {
		return this.tpteamUsers;
	}

	public void setTpteamUsers(Set<TpteamUser> tpteamUsers) {
		this.tpteamUsers = tpteamUsers;
	}

}
