package edu.harvard.fas.rbrady.tpteam.tpbridge.hibernate;

// Generated Nov 10, 2006 5:22:58 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * TestExecution generated by hbm2java
 */
public class TestExecution implements java.io.Serializable, Comparable<TestExecution> {

	// Fields    

	private static final long serialVersionUID = 1L;

	private int id;

	private TpteamUser tpteamUser;

	private Test test;

	private Character status;

	private Date execDate;

	private String comments;

	// Constructors

	/** default constructor */
	public TestExecution() {
	}

	/** minimal constructor */
	public TestExecution(int id) {
		this.id = id;
	}

	/** full constructor */
	public TestExecution(int id, TpteamUser tpteamUser, Test test,
			Character status, Date execDate, String comments) {
		this.id = id;
		this.tpteamUser = tpteamUser;
		this.test = test;
		this.status = status;
		this.execDate = execDate;
		this.comments = comments;
	}

	// Property accessors
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public TpteamUser getTpteamUser() {
		return this.tpteamUser;
	}

	public void setTpteamUser(TpteamUser tpteamUser) {
		this.tpteamUser = tpteamUser;
	}

	public Test getTest() {
		return this.test;
	}

	public void setTest(Test test) {
		this.test = test;
	}

	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	public Date getExecDate() {
		return this.execDate;
	}

	public void setExecDate(Date execDate) {
		this.execDate = execDate;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}
	
	/**
	 * A descending order comparator so test execution results
	 * will be returned with most recent result "on top"
	 */
	public int compareTo(TestExecution anotherTestExecution) {  
	    return -this.execDate.compareTo(anotherTestExecution.getExecDate());    
	  }

}
